### ISSUE TITLE
webui bug when editing resource

### ISSUE THREAD

**Issue by cjdcordeiro** [slipstream/SlipStreamWebUI#105]

**Comment by cjdcordeiro** [comment]
<img width="886" alt="screen shot 2018-03-02 at 1 29 27 pm" src="https://user-images.githubusercontent.com/4047767/36899102-e4cd6c20-1e1d-11e8-8a93-1123b41b7662.png">

**Comment by loomis** [comment]
This seems to be a race condition when the editor data is cached before it has been updated by the resource refresh event. I was only able to reproduce the problem occasionally and never reliably. After #107 I've not been able to see the problem again, but this might just be from bad luck.
