### ISSUE TITLE
usage: Number of VMs hours are wrong

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamWebUI#139]
It uses `cardinality:instanceID` which give the number of unique VMs for the specified period of time.
Then the value is divided by 60 which has no meaning in this case.

The attribute `count` of the reply should be used and divided by 60 because every document represent a minute of the life of a VM.

**Comment by 0xbase12** [comment]
Fixed in following commit slipstream/SlipStreamWebUI@bb9d8e3
