### ISSUE TITLE
cimi: not all operations are displayed

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamWebUI#144]
It seems that only the first "extra" action is displayed.

It happens for example with the `connector` resource with the `nuvlabox` template.

As privileged user
![screen shot 2018-05-01 at 15 43 08](https://user-images.githubusercontent.com/2462866/39475145-6e8071a2-4d57-11e8-85a3-02e1d8e57cc2.png)

As standard user
![screen shot 2018-05-01 at 15 28 17](https://user-images.githubusercontent.com/2462866/39475146-6eaa17f0-4d57-11e8-8b9c-3dadf10268f0.png)

**Comment by 0xbase12** [comment]
Fixed in following commit 1e5a619
