### ISSUE TITLE
Webui not working with advanced optimizations because of issue in reagent 0.8.0

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStreamWebUI#145]
Console log:
```
TypeError: b.PropTypes is undefined[Learn More]
webui.js:4049:220
````

Perhaps it's linked to existing issues:
https://github.com/reagent-project/reagent/blob/master/docs/0.8-upgrade.md

Should we change back the version and wait for a fix or investigate more ?

**Comment by loomis** [comment]
@0xbase12 Did the workspace where you compiled the code have a `node_modules` subdirectory?  If so, can you retry with the latest commit e00d568631ad076963f5f65f6dbc78c646233087?

**Comment by 0xbase12** [comment]
After check, the issue is coming from the [cljsjs/react-date-range] dependency which is not compatible with last react version. The react-date-range is being refactored (https://github.com/Adphorus/react-date-range) so we need to wait or use an alternative calendar for usage view.
