### ISSUE TITLE
sign in form not visible

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamWebUI#155]
The sign in form is not visible (at least on Nuvla). Ensure that the form is visible and works correctly.

**Comment by 0xbase12** [comment]
This is due to missing `Self-registration` template on Nuvla

**Comment by elegoff** [comment]
Confirmed that once the `self-registration` was added, the signup menu showed up. I have also added the user-templates for :

**Comment by elegoff** [comment]
Also added HNSciCloud organizations and “Biosphere” user templates

**Comment by loomis** [comment]
After a bit of thought, probably **not** loading the self registration user template is the correct behavior.  Like this, administrators can turn off the self registration is they want to.  However, you should check that this behavior is explicit and correct in the self registration user template.

**Comment by loomis** [comment]
No changes.  Behavior is correct.
