### ISSUE TITLE
refactor login to use separate page rather than modal

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamWebUI#16]
Since integration of the WebUI code in the current UI can only be done by replacing sections of the current UI, the login/logout widget must be refactored to appear as a section rather than a widget.

**Comment by loomis** [comment]
The merge PR is the first refactoring for moving the login process to a separate page. It also renames the app from `app.js` to `webui.js` to avoid conflicts with the current UI.

**Comment by mebster** [comment]
Here's a nice layout for multi-service authentication: https://w3layouts.com/facebook-twitter-google-login-page/  It's hopefully close to this layout, simply replacing the dropdown with a two column table.  Done with bootstrap, the two column should fold into a single column on mobile.  On success, for the moment, if we don't have time to implement a redirect, we could simply add something like a welcome message and two large icons for example for the 1. dashboard,  2. app, 3. Workspace and 4. Profile.

**Comment by loomis** [comment]
See #24 for last comment.
