### ISSUE TITLE
Page width larger than the window and cannot scroll horizontally

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamWebUI#177]
When the results table is larger than the available width, the whole page gets out of the windows limit (on the right).
This is probably related to the size of the left "menubar".

![screen shot 2018-07-20 at 11 56 15](https://user-images.githubusercontent.com/2462866/43027038-aee2fe44-8c78-11e8-9201-c2641e1ee989.png)

**Comment by loomis** [comment]
@lionel The fix (from @0xbase12) is on Nuvla.  Please verify that this fixes this problem.
