### ISSUE TITLE
invalid resource type bug?

### ISSUE THREAD

**Issue by cjdcordeiro** [slipstream/SlipStreamWebUI#202]
<img width="997" alt="screen shot 2018-08-08 at 9 17 45 am" src="https://user-images.githubusercontent.com/4047767/43822315-14efa8be-9aec-11e8-97b3-a48a96ece6ae.png">

to replicate, go to https://nuv.la/webui/cimi/service-offer/af6ee772-650c-4514-9196-5ba6463aba7b

**Comment by loomis** [comment]
Can't reproduce this.  Correct error message is returned for me on Nuvla with v3.57.

<img width="1060" alt="screen shot 2018-08-28 at 09 40 31" src="https://user-images.githubusercontent.com/490506/44708116-9243a580-aaa6-11e8-9ea4-ca15bac24291.png">
