### ISSUE TITLE
Deployment workflow 

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamWebUI#270]
Following notes from this morning's discussion with Cal.

**UI**

See all -> show in modal
List / tiles view (start with tiles)
Search field should search in attributes: in name, description and comments.

I used Netflix as an example of grouping items, using predefined filters:

![image-1](https://user-images.githubusercontent.com/419519/46660736-f7b3a780-cbb7-11e8-827d-997b240134d2.jpg)

Potential filters:
* **Search**
* Currently trending** 
* My apps
* Currently running** 
* Recently used
* My favorites
* “By type”
* **Browse**

In bold (search and browse) are must have. One of those (**) will illustrate the potential of a predefined filter to allow Alice to more quickly find what she's looking for. browse is need by Clara to organise her work.

Feel free to suggest different filters.

We would need a new favorite resource to implement this filter.

Deploy button (operate in modal)

The following workflow will be implemented in a Semantic-UI *steps* widget in a *modal*:
* Choose template (version?) or create new (and name/tag)
* Cloud / credentials 
* Resources (e.g. cpu, ram, disk)
* Params
* Data (services?)
* Deploy
* Redirect to newly created Deployment page

A *Deploy/Play* button will be visible at the bottom of the widget. It will be enabled once sufficient information is available. Each step requiring inputs will be highlighted, such that the user knows which step requires particular attention. Here's an example of *steps*:
![screenshot 2018-10-09 at 11 44 24](https://user-images.githubusercontent.com/419519/46661183-f59e1880-cbb8-11e8-821a-7ae49a7c9ba3.png)

**Comment by konstan** [comment]
The proposed filters are application driven.  
I believe, the generic **Search** can be used to find data volumes as well.  Would be good to have predefined data driven filters as well, e.g. volumes I can see, my favorite volumes. 
Then for the workflow, if Clara defined apps that use/process the data volumes I can see, I want to be able to know that. I.e. it's "up side down", I don't start from applications, but from data, and then I deploy an app (where the data is). IMHO, this is what Alices in big data projects are doing.

**Comment by mebster** [comment]
Ok, so you suggest we have another filter for 'my volumes' or 'my data'. From there, clicking on the deploy/play button of a specific data tile will bring an alternate workflow, where Alice will be presented with a list of compatible apps.

The 'my data' filter will work on what?  'services', which are for example running deployments data apps (e.g. NFS, GlusterFS, fuse FS)?  Or a query on external objects resource?  There are a number of complications with all this, but am I capturing your first order requirements?

**Comment by mebster** [comment]
Discussion continues on the wiki page: https://github.com/SixSq/tasklist/wiki/Deployment-workflow
