### ISSUE TITLE
Data workflow

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStreamWebUI#290]

**Comment by 0xbase12** [comment]
https://github.com/slipstream/SlipStreamWebUI/pull/new/task/data-workflow

**Comment by loomis** [comment]
### Data Selection

 - [ ] query user information for credentials to extract the list of cloud infrastructures (Q1)
 - [ ] define hardcoded query of service offers for GNSS (Q2)
 - [ ] get time period (date and time) constraints from form on the UI (Q3)
 - [ ] combine above queries (Q1, Q2, Q3) to obtain a list of relevant service offers
 - [ ] display the results of the combined query as a "card" for each data mimetype
 - [ ] card contain the mimetype and the number of objects selected
 - [ ] provide a button ("process") that selects the dataset to analyze and to bring up the deployment dialog

### Deployment Dialog

 - [ ] match applications to dataset by querying for those that have a matching "dataAcceptContentTypes" value, visualize as a list
 - [ ] user selects a single application to deploy from the list
 - [ ] user selects a single credential/cloud if dataset identifies more than one
 - [ ] user sets applications parameters (application parameters, CPU/RAM/Disk, etc.)
 - [ ] user clicks on "deploy" button once all information has been provided

### Deployment Action
 - [ ] creates a deployment resource from template and parameters
 - [ ] adds selected data objects (ServiceOffers or ExternalObjects) to deployment
 - [ ] starts the deployment
 - [ ] application downloads deployment information to obtain objects to analyze
 - [ ] option 1: application uses GNSS C++ library to download required objects
 - [ ] option 2: application mounts via S3 FUSE FS the buckets containing data

**Comment by loomis** [comment]
The agreement with @konstan is to standardize on the following attributes in the service offer for describing the data objects of GNSS:

 - `data:location`: geo-point that can be represented in any format recognized by Elasticsearch
 - `data:contentType`: MIME type describing the format of the data
 - `data:bytes`: size of the content in bytes
 - `data:timestamp`: single timestamp for the data in ISO8601 format (ideally in GMT)
 - `data:protocols`: list of protocols by which data are accessible

For this a generic `data` namespace will need to be created.  Data matching features will be hardcoded to use values in this namespace.

**Comment by loomis** [comment]
The `data` namespace has been created on Nuvla.  The above attribute descriptions have also been created.  All the attributes in the `price`, `resource`, and `aws` namespaces have been updated to use the latest schema.

**Comment by loomis** [comment]
The data attributes have been added manually to the Elasticsearch mapping for Nuvla:

```json
          "data:bytes" : {
            "type" : "long"
          },
          "data:contentType" : {
            "type" : "keyword"
          },
          "data:location" : {
            "type" : "geo_point"
          },
          "data:protocols" : {
            "type" : "keyword"
          },
          "data:timestamp" : {
            "type" : "date"
          },
```
