### ISSUE TITLE
upgrade shadow-cljs

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamWebUI#292]
Upgrade to the latest shadow-cljs (2.7.2) and closure (v20181028) releases. These will work with the current and latest ClojureScript releases.

**Comment by loomis** [comment]
Unfortunately, this requires an upgrade to the latest ClojureScript release as well.  The compilation fails with this exception:

```
Caused by: java.lang.RuntimeException: Unable to resolve var: comp/*source-map-data-gen-col* in this context
```

**Comment by loomis** [comment]
The `project.clj` file has been updated to take dependency versions as much as possible from the parent module.

**Comment by theronic** [comment]
Ran into a similar problem on another project. Bumping Clojure and Clojurescript versions in deps.edn solved it for me.
