### ISSUE TITLE
layout changes for gnss

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamWebUI#337]
The following (minor) changes were requested for the embedded WebUI interface for GNSS:

 - [x] Completely remove application logo in upper left hand corner.
 - [ ] Rename "deployment" to "applications" (or some other term that is more familiar).
 - [x] Remove the application footer.
 - [x] Swap the order of "data" and "deployment" in the sidebar ("data" before "deployment").
 - [x] On user login, go instead to the "data" page (or to something other than the login profile).
 - [x] Change the "URL" label on ready deployments to "open", "open application", "go to application" or something similar.
 - [x] Add "select/deselect" to message on the dataset page.
 - [x] Choose a different icon for "process" on the dataset page that will not be confused with a "settings" icon.

More intrusive changes to the interface have been created as separate tickets.

**Comment by mebster** [comment]
We also discussed adding back on the left menu:
- [ ] 'applications' and
- [ ] 'app store'.

The underlying issue with the term 'deployment' is that it's not intuitive for users.  We use this term to say: 'running applications', and perhaps that's an interesting path to explore.

**Comment by loomis** [comment]
- Data/deployment order has been changed in sidebar and on welcome page.
 - Redirect on login now goes back to welcome page.
 - URL was changed to "access service".
 - Rocket icon is now used for "process".

**Comment by loomis** [comment]
For unimplemented comments see #340.

**Comment by mebster** [comment]
> URL was changed to "access service".
I would prefer we avoid using a new term (aka not used in the UI at the moment) like 'service' and use 'go to app' instead.

**Comment by loomis** [comment]
I've reverted to "URL" and added this comment to the other ticket about deployment renaming.

**Comment by mebster** [comment]
I think 'go to app' is better than 'URL' and it doesn't introduce a new term.

**Comment by loomis** [comment]
I think it is much worse. It uses an existing term (app) to refer to something with a different name (deployment).

**Comment by mebster** [comment]
'go to deployment' or 'access deployment'?

**Comment by loomis** [comment]
Possibly, but then that brings up the issue on the naming of the deployment tab.  That was why I moved this to the other ticket (#340).

**Comment by mebster** [comment]
I don't think we'll have a short term alternative for 'deployment'. So this terms stays for the moment.  Therefore, I think my proposal is consistent with the current set of terms, without introducing new ones.
