### ISSUE TITLE
Missing form for coupon when registering via Human Brain Project

### ISSUE THREAD

**Issue by elegoff** [slipstream/SlipStreamWebUI#346]
Users from Human Brain Project can no longer sign up since there is no field to provide their exoscale coupon

**Comment by 0xbase12** [comment]
This is related to missing resource-metadata for exoscale coupon.
`exoscale/config/src/com/sixsq/slipstream/ssclj/resources/credential_template_cloud_exoscale_coupon.clj`

**Comment by 0xbase12** [comment]
Fixed and Nuvla was hotpatched. @elegoff  can you please retry to register with coupon
