### ISSUE TITLE
bug when deselecting "inactive runs"

### ISSUE THREAD

**Issue by cjdcordeiro** [slipstream/SlipStreamWebUI#35]
go to dashboard, click on "Include inactive runs" and move to the last page (or any other page where only inactive runs appear). 

Deselect the "Include inactive runs" and your active runs will not appear back in

**Comment by loomis** [comment]
The problem is because the initial values of the internal reagent atoms are not taken from the current database values and the values for the active flag were not consistently 0 or 1.
