### ISSUE TITLE
Suggestion for welcome, registration and login page mockups

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamWebUI#49]
Here's a first attempt at creating mock-ups, using OmniGraffle, to draft web ui pages.

This is linked to the new workflows created for registration, login and organisation membership management: https://github.com/SixSq/tasklist/issues/1280.

The omniGraffle file is [here](https://www.dropbox.com/sh/w7s6oskyy1fj7dp/AACuwo3LevO530bkI17Z_-9Ea?dl=0) and the pdf [here](https://www.dropbox.com/sh/jpxz3sezau8ev1a/AAB2PQDPGOgJVJ7735LxwusCa?dl=0).

**Comment by mebster** [comment]
Thee are two things here:
 - Is this a useful way of defining UI pages?
 - Do implement the three pages as proposed?

**Comment by cjdcordeiro** [comment]
https://github.com/SixSq/tasklist/issues/1280#issuecomment-322751014

**Comment by loomis** [comment]
https://github.com/SixSq/tasklist/issues/1280#issuecomment-323004432

**Comment by mebster** [comment]
Closing this issue. Moving the discussion to the UI wiki: https://github.com/SixSq/tasklist/wiki/Cubic-as-main-UI
