### ISSUE TITLE
provide better positioning for login elements

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamWebUI#52]
Elements should be better positioned. The result for a mobile display is ok (single stack) but not for other displays. E.g. the GitHub (for example) button should be in a separate column, not under the key/secret block. Perhaps a 3-column layout would work better. Otherwise, the u/p and k/s blocks could be stacked and other buttons on a second column?

**Comment by cjdcordeiro** [comment]
you might maybe take the opportunity to address https://github.com/slipstream/SlipStreamUI/issues/568

**Comment by loomis** [comment]
The 2 column display is used on larger devices and a single column on smaller ones.
