### ISSUE TITLE
update usage page to use metering

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamWebUI#75]
Update the usage page to use the new metering resource.  The page should display information similar to the existing page, but take the information from queries of the metering resources.

**Comment by 0xbase12** [comment]
- [ ] Add usage metering for all clouds in a semantic statistic component below table of metering
- [ ] for admin add users filtering

- [ ] (will be good to have pie chart)

**Comment by mebster** [comment]
I think the summary should go above the table.

**Comment by 0xbase12** [comment]
slipstream/SlipStreamUI@3926f9c
